services:
  accounts:
    image: "simonjmorgan/accounts:1.0"
    container_name: accounts-microservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
  loans:
    image: "simonjmorgan/loans:1.0"
    container_name: loans-microservice
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
  cards:
    image: "simonjmorgan/cards:1.0"
    container_name: cards-microservice
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
networks:
  bankapp:
    driver: "bridge"